Repository cms-gem-daq-project/xhal, pull requests merged in 2018-05, with the labels that each got.

#64 Update sca.py to run from the card
  python/reg_interface/sca.py
  xcompile/lib_rw_ctp7/rwreg.cc
Labels: Priority: High

#59 Reg interface prompt class separation
  python/reg_interface/reg_interface.py
  python/reg_interface/ri_prompt.py
  python/reg_interface/ri_prompt_extended.py
Labels: Priority: Medium, Type: Enhancement, Type: New Tag

#61 New Feature: Programming GBTs over fiber link
  python/reg_interface/gbt.py
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#66 release 3.2.0 patch1
  python/daq_suite/daq_suite/helper_main.py
  python/daq_suite/daq_suite/rw_reg.bkp
  python/daq_suite/daq_suite/rw_reg.py
  python/daq_suite/daq_suite/settings.py
  python/daq_suite/daq_suite/urls.py
  python/daq_suite/daq_suite/views.py
  python/daq_suite/start.sh
  python/reg_interface/ri_prompt_extended.py
  python/reg_interface/rw_reg.py
Labels: Priority: Critical, Type: Bugfix

#67 Bugfix program-fpga
  python/reg_interface/sca.py
Labels: Priority: Critical, Type: Bugfix

#68 Fix exe mode when executing on card
  python/reg_interface/reg_interface.py
Labels: Priority: Critical, Type: Bugfix

#70 Update master to reflect changes in develop
  .github/uploads.cfg
  .gitignore
  Makefile
  Makefile_ctp7
  README.md
  etc/gem_amc_v3_1_4_GBT.xml
  etc/optohybrid_registers.xml
  include/xhal/rpc/calibration_routines.h
  include/xhal/rpc/daq_monitor.h
  include/xhal/rpc/optohybrid.h
  include/xhal/rpc/utils.h
  include/xhal/rpc/vfat3.h
  lib/x86_64/.gitignore
  lib/x86_64/libwiscrpcsvc.so
  python/daq_suite/daq_suite/helper_main.py
  python/daq_suite/daq_suite/rw_reg.bkp
  python/daq_suite/daq_suite/rw_reg.py
  python/daq_suite/daq_suite/settings.py
  python/daq_suite/daq_suite/urls.py
  python/daq_suite/daq_suite/views.py
  python/daq_suite/start.sh
  python/reg_interface/gbt.py
  python/reg_interface/reg_interface.py
  python/reg_interface/ri_prompt.py
  python/reg_interface/ri_prompt_extended.py
  python/reg_interface/rw_reg.py
  python/reg_interface/sca.py
  python/reg_interface/test.py
  setup.sh
  src/common/rpc_manager/calibration_routines.cc
  src/common/rpc_manager/daq_monitor.cc
  src/common/rpc_manager/optohybrid.cc
  src/common/rpc_manager/utils.cc
  src/common/rpc_manager/vfat3.cc
  src/common/rpc_standalone_client/rwreg.cpp
  src/common/utils/XHALXMLParser.cpp
  test/units/parse_t.cpp
  xcompile/lib_rw_ctp7/Makefile
  xcompile/lib_rw_ctp7/rwreg.cc
Labels: Priority: High, Status: Review Needed, Type: Maintenance
