Repository cms-gem-daq-project/xhal, pull requests merged in 2018-02, with the labels that each got.

#40 Removing check for top node, adding CC7 libwiscrpcsvc, adding doc ali…
  lib/x86_64/libwiscrpcsvc.so
  python/reg_interface/reg_interface.py
  python/reg_interface/rw_reg.py
Labels: Priority: High, Status: Review Needed, Type: Bugfix, Type: Enhancement

#45 Propagating Andrew's improvements (address table pickling)
  python/reg_interface/rw_reg.py
Labels: Priority: Medium, Status: Completed, Status: Review Needed, Type: Enhancement

#43 New Feature: added functionality for parallel sbit scan vs. arbitrary scan register
  include/xhal/rpc/calibration_routines.h
  setup.sh
  src/common/rpc_manager/calibration_routines.cc
Labels: Priority: High, Status: Completed, Type: Enhancement

#44 New Feature: genScanLocal uses current pulse mode of calibration module #20
  include/xhal/rpc/calibration_routines.h
  src/common/rpc_manager/calibration_routines.cc
Labels: Priority: Medium, Status: In Progress, Type: Enhancement

#47 Adding update_lmdb method to reg_interface
  python/reg_interface/reg_interface.py
  python/reg_interface/rw_reg.py
Labels: Priority: High, Status: Completed, Status: Review Needed, Type: Enhancement

#53 Fixing compilation against system-wide libwiscrpcsvc
  Makefile
  lib/x86_64/.gitignore
  lib/x86_64/libwiscrpcsvc.so
Labels: Priority: High, Type: Enhancement
