Repository cms-gem-daq-project/xhal, pull requests merged in 2019-07, with the labels that each got.

#121 Bring core functionnality for the templated RPC calls
  xhalcore/include/xhal/rpc/call.h
  xhalcore/include/xhal/rpc/common.h
  xhalcore/include/xhal/rpc/compat.h
  xhalcore/include/xhal/rpc/helper.h
  xhalcore/include/xhal/rpc/register.h
Labels: PR: reviewed-approved

#123 Add more types to the templated RPC
  xhalcore/include/xhal/rpc/common.h
  xhalcore/include/xhal/rpc/helper.h
Labels: PR: reviewed-approved, Type: Enhancement

#124 Implementing callers for SCAADC readouts
  xhalcore/include/xhal/rpc/sca.h
  xhalcore/include/xhal/rpc/utils.h
  xhalcore/src/common/rpc_manager/sca.cc
  xhalcore/src/common/rpc_manager/utils.cc
Labels: PR: reviewed-approved, Priority: High, Status: In Progress, Status: Review Needed
