Repository cms-gem-daq-project/xhal, pull requests merged in 2019-04, with the labels that each got.

#107 [hotfix] Add block nodes for legacy
  xhalcore/include/xhal/utils/XHALXMLNode.h
  xhalcore/src/common/utils/XHALXMLParser.cpp
Labels: PR: reviewed-approved, Type: Bugfix

#104 Added Interface for Getting ChipID from RPC Function
  xhalcore/include/xhal/rpc/vfat3.h
  xhalcore/src/common/rpc_manager/vfat3.cc
Labels: PR: reviewed-approved, Priority: High, Status: Review Needed, Type: Enhancement

#103 Bug fixed in type definition of sbit readout output file
  xhalcore/src/common/rpc_manager/amc.cc
Labels: PR: reviewed-approved, Priority: Medium, Type: Bugfix, Type: Maintenance

#110 Bug Fix: Missing end of line character in GBT Results File
  python/reg_interface_gem/core/gbt_utils_extended.py
Labels: PR: reviewed-approved, Priority: High, Type: Bugfix, Type: Enhancement
