Repository cms-gem-daq-project/xhal, pull requests merged in 2019-05, with the labels that each got.

#114 Adding empty hostname verification
  python/reg_interface_gem/scripts/gem_reg.py
Labels: PR: reviewed-approved, Priority: High, Type: Bugfix

#113 Allow multiple GBT phase scan results to be written to the same file
  python/reg_interface_gem/core/gbt_utils_extended.py
  python/reg_interface_gem/test/.gitattributes
  python/reg_interface_gem/test/data/test_saveGBTPhaseScanResults_AppendToFile.root
  python/reg_interface_gem/test/data/test_saveGBTPhaseScanResults_NewFile.root
  python/reg_interface_gem/test/test_saveGBTPhaseScanResults.py
Labels: PR: reviewed-approved, Priority: High, Status: Review Needed, Type: Bugfix

#112 New Feature: Interface for repeated register read
  python/reg_interface_gem/core/reg_extra_ops.py
  xhalcore/include/xhal/rpc/amc.h
  xhalcore/include/xhal/rpc/utils.h
  xhalcore/src/common/rpc_manager/amc.cc
  xhalcore/src/common/rpc_manager/utils.cc
Labels: PR: reviewed-approved, Priority: Critical, Status: Review Needed, Type: Enhancement
