Repository cms-gem-daq-project/xhal, pull requests merged in 2019-03, with the labels that each got.

#101 [hotfix] Adapt exception class for const correctness
  xhalcore/include/xhal/utils/Exception.h
Labels: PR: reviewed-approved, Type: Bugfix

#102 New Feature: Added link monitoring for GBT & VFATs
  python/reg_interface_gem/core/gbt_utils_extended.py
  python/reg_interface_gem/core/reg_extra_ops.py
  python/reg_interface_gem/core/ri_prompt_extended.py
  python/reg_interface_gem/pkg/setup.cfg
  python/reg_interface_gem/requirements.txt
  xhalcore/include/xhal/rpc/daq_monitor.h
  xhalcore/include/xhal/rpc/gbt.h
  xhalcore/src/common/rpc_manager/daq_monitor.cc
  xhalcore/src/common/rpc_manager/gbt.cc
  xhalcore/src/common/rpc_manager/utils.cc
Labels: PR: reviewed-approved, Priority: Medium, Status: Review Needed, Type: Enhancement

#106 [Bugfix] IndentationError in gbt_utils_extended.py
  python/reg_interface_gem/core/gbt_utils_extended.py
Labels: PR: reviewed-approved

#105 Updating sbitRateScan to comply with ctp7_modules PR #102
  xhalcore/include/xhal/rpc/calibration_routines.h
  xhalcore/src/common/rpc_manager/calibration_routines.cc
Labels: PR: reviewed-approved, Priority: High, Status: Review Needed, Type: Enhancement
